import {
  InstagramLogo,
  TelegramLogo,
  List,
  X,
  AppleLogo,
  SpotifyLogo,
  YoutubeLogo,
  GithubLogo,
  FileArrowDown,
  CaretRight,
  DotsSix,
  HouseSimple,
  ReadCvLogo,
  Info,
  Stack,
  GraduationCap,
  Lifebuoy,
  BagSimple,
  UserGear,
  HardHat,
  User,
  Waveform,
  AddressBook,
} from "@phosphor-icons/react/dist/ssr";

export const ICON_MAP = {
  instagram: InstagramLogo,
  telegram: TelegramLogo,
  list: List,
  close: X,
  dots: DotsSix,
  apple: AppleLogo,
  spotify: SpotifyLogo,
  youtube: YoutubeLogo,
  github: GithubLogo,
  "caret-right": CaretRight,
  "download-file": FileArrowDown,
  "house-simple": HouseSimple,
  "read-cv": ReadCvLogo,
  info: Info,
  stack: Stack,
  graduation: GraduationCap,
  lifebuoy: Lifebuoy,
  bag: BagSimple,
  user: UserGear,
  hardhat: HardHat,
  userProfile: User,
  waveform: Waveform,
  addressBook: AddressBook,
} as const satisfies Record<
  string,
  React.FC<React.SVGAttributes<SVGSVGElement>>
>;

export type IIconName = keyof typeof ICON_MAP;
